# Generated by Django 4.2.7 on 2023-11-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_spamnumber_cuser_is_active_cuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='spamnumber',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='spamnumber',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spamnumber',
            name='spam_likelihood',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spamnumber',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='spamnumber',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
