# Generated by Django 4.2.7 on 2023-11-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_cuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
